#!/usr/bin/env bash

. `dirname $0`/ploy-lib.sh
CONFIG_PATH=`expand_path $1`
cd `dirname $0`/..

if [ `id -u` != "0" ]; then
  fail "Please run this script as root: sudo $0 $@"
fi

if [ -z "$CONFIG_PATH" ]; then
  fail "Missing the first argument: the path to the config file"
fi

if ! [ -f "$CONFIG_PATH" ]; then
  fail "Config file not found at $CONFIG_PATH"
fi

# Install project's runtime dependencies
depend Dependfile runtime

# App state
mkdir -p /app/var/log
mkdir -p /app/var/tmp
chown app:app /app/var/log
chown app:app /app/var/tmp

rm -rf log
ln -sf /app/var/log log

rm -rf tmp
ln -sf /app/var/tmp tmp

exec bin/chef-solo -c $PWD/config/chef-solo.rb -j $CONFIG_PATH
